import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    backgroundColor: 'white',
    flex: 1,
  },
  contentContainer: {
    marginTop: 16,
    paddingHorizontal: 16,
  },
  tabHeader: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 6,
  },
  tabHeaderText: {
    color: '#1c1c1c',
    fontSize: 20,
    lineHeight: 24,
    fontFamily: 'RethinkSans-Bold',
  },
  profileContent: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 3,
  },
  profilePictureContainer: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileInfoContainer: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarContainer: {
    position: 'relative',
    width: 70,
    height: 70,
  },
  avatarImage: {
    width: 70,
    height: 70,
    borderRadius: 35,
  },
  avatarPlaceholder: {
    width: 70,
    height: 70,
    backgroundColor: '#333333',
    borderRadius: 35,
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarInitials: {
    fontSize: 24,
    fontFamily: 'RethinkSans-SemiBold',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  editIconContainer: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 32,
    height: 32,
    backgroundColor: '#1A2373',
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  userInfoContainer: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    // paddingVertical: 16,
    paddingHorizontal: 20,
    gap: 4,
    marginTop: 16,
  },
  userName: {
    fontSize: 16,
    lineHeight: 20,
    color: '#1c1c1c',
    fontFamily: 'RethinkSans-SemiBold',
  },
  userEmail: {
    fontSize: 12,
    lineHeight: 14,
    color: '#494949',
    fontFamily: 'RethinkSans-Regular',
  },
  accountSettingsContainer: {
    width: '100%',
    paddingHorizontal: 16,
    gap: 24,
    marginTop: 32,
  },
  sectionHeading: {
    fontSize: 16,
    color: '#1c1c1c',
    marginBottom: 12,
    fontFamily: 'RethinkSans-SemiBold',
  },
  settingsList: {
    width: '100%',
    gap: 8,
  },
  settingsItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: 48,
    paddingHorizontal: 16,
    backgroundColor: '#FCFCFC',
    borderRadius: 8,
    borderWidth: 0.2,
    borderColor: '#C7C8C9',
  },
  settingsItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  settingsItemRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  settingsItemText: {
    fontSize: 14,
    color: '#1c1c1c',
    fontFamily: 'RethinkSans-Regular',
  },
  frequencyText: {
    fontSize: 14,
    color: '#6B7280',
    fontFamily: 'RethinkSans-Regular',
  },
  logoutText: {
    fontSize: 14,
    fontFamily: 'RethinkSans-Medium',
    color: '#FF5A3D',
    textAlign: 'center',
    marginTop: 32,
    marginBottom: 20,
  },
  logoutModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  logoutModalContent: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 24,
    width: '100%',
    maxWidth: 343,
    alignItems: 'center',
  },
  logoutIconContainer: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#FBEAEA',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  logoutModalTitle: {
    fontSize: 20,
    fontFamily: 'RethinkSans-Bold',
    color: '#1c1c1c',
    marginBottom: 8,
  },
  logoutModalMessage: {
    fontSize: 14,
    fontFamily: 'RethinkSans-Regular',
    color: '#494949',
    textAlign: 'center',
    marginBottom: 24,
  },
  logoutModalButtons: {
    flexDirection: 'column',
    gap: 12,
    width: '100%',
  },
  logoutModalNoButton: {
    height: 48,
    backgroundColor: '#FCFCFC',
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#C7C8C9',
  },
  logoutModalNoButtonText: {
    fontSize: 14,
    fontFamily: 'RethinkSans-Medium',
    color: '#1c1c1c',
  },
  logoutModalYesButton: {
    height: 48,
    backgroundColor: '#FF5A3D',
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#BBBCBC',
  },
  logoutModalYesButtonText: {
    fontSize: 14,
    fontFamily: 'RethinkSans-Medium',
    color: 'white',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  openButton: {
    backgroundColor: '#ff5a3d',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 10,
  },
  openButtonText: {
    color: '#fff',
    fontSize: 16,
    fontFamily: 'RethinkSans-SemiBold',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: '5%',
    paddingTop: 12,
    maxHeight: '90%',
  },
  modalHeader: {
    alignItems: 'center',
    marginBottom: 20,
  },
  dragHandle: {
    width: 40,
    height: 4,
    backgroundColor: '#D1D5DB',
    borderRadius: 2,
    marginTop: 8,
  },
  logoContainer: {
    alignItems: 'center',
    marginBottom: 32,
  },
  logoImage: {
    width: 243,
    height: 103,
  },
  buttonsContainer: {
    width: '100%',
    marginBottom: 24,
  },
  socialButton: {
    width: '100%',
    height: 50,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#babec6',
    marginBottom: 15,
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 8,
    flexDirection: 'row',
  },
  socialIcon: {
    height: 25,
    width: 25,
    marginRight: 10,
  },
  appleIcon: {
    height: 35,
    width: 35,
    marginRight: 10,
  },
  socialButtonText: {
    color: '#000',
    fontFamily: 'RethinkSans-SemiBold',
    fontSize: 16,
  },
  emailButton: {
    width: '100%',
    height: 50,
    borderRadius: 10,
    backgroundColor: '#ff5a3d',
    marginBottom: 15,
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 8,
  },
  emailButtonText: {
    color: '#fff',
    fontSize: 16,
    fontFamily: 'RethinkSans-SemiBold',
  },
  emailButtonSecondary: {
    width: '100%',
    height: 50,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#babec6',
    backgroundColor: 'transparent',
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 8,
  },
  emailButtonSecondaryText: {
    color: '#000',
    fontSize: 16,
    fontFamily: 'RethinkSans-SemiBold',
  },
  footer: {
    width: '100%',
    paddingTop: 20,
    paddingBottom: 10,
    alignItems: 'center',
  },
  footerText: {
    fontSize: 13,
    fontFamily: 'RethinkSans-Regular',
    color: '#555',
    textAlign: 'center',
    lineHeight: 18,
    paddingHorizontal: 10,
  },
});

export default styles;

